#!/usr/bin/env bash
# bootstrap.sh — one-time setup for a Medoc Health developer machine.
#
#   git clone git@github.com:MedocHealth/claude_md.git
#   cd claude_md && bash scripts/bootstrap.sh
#
# Installs the machine-wide non-negotiable rules so that EVERY Medoc repo you work in
# carries them, whether or not you cloned the rest of the workspace. Safe to re-run.

set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
POLICY_SRC="$REPO/managed-policy/CLAUDE.md"
DRY=1; [ "${1:-}" = "--write" ] && DRY=0

case "$(uname -s)" in
  Darwin) POLICY_DST="/Library/Application Support/ClaudeCode/CLAUDE.md" ;;
  Linux)  POLICY_DST="/etc/claude-code/CLAUDE.md" ;;
  *)      echo "Unsupported OS $(uname -s). On Windows the path is C:\\Program Files\\ClaudeCode\\CLAUDE.md" >&2; exit 1 ;;
esac

echo "Medoc Health — Claude Code bootstrap"
echo "  repo:   $REPO"
echo "  policy: $POLICY_DST"
echo

[ -f "$POLICY_SRC" ] || { echo "missing $POLICY_SRC — is this the claude_md repo?" >&2; exit 1; }

if [ -f "$POLICY_DST" ] && cmp -s "$POLICY_SRC" "$POLICY_DST"; then
  echo "✓ managed policy already current"
else
  if [ "$DRY" -eq 1 ]; then
    echo "· would install managed policy (needs sudo)"
  else
    echo "· installing managed policy — sudo required (writes outside your home directory)"
    sudo mkdir -p "$(dirname "$POLICY_DST")"
    sudo cp "$POLICY_SRC" "$POLICY_DST"
    sudo chmod 644 "$POLICY_DST"
    echo "✓ managed policy installed"
  fi
fi

# Optional convenience: if claude_md sits inside a workspace directory alongside other
# Medoc repos, drop a small stub there so the workspace root also carries the map pointer.
WS="$(cd "$REPO/.." && pwd)"
siblings=$(find "$WS" -maxdepth 2 -name .git -not -path "$REPO/*" 2>/dev/null | wc -l | tr -d ' ')
if [ "$siblings" -gt 1 ]; then
  STUB="$WS/CLAUDE.md"
  read -r -d '' STUB_BODY <<'STUB_EOF' || true
# Medoc Health workspace

Each repository below carries its own `CLAUDE.md`, generated from `claude_md/repos.yaml`.
Start there — it tells you whether the repo is live, what will bite you, and what else you
must change. The non-negotiable rules are installed machine-wide by
`claude_md/scripts/bootstrap.sh`.

Whole-workspace reference (89 repos, which twin is live, where the secrets are):
@claude_md/WORKSPACE-MAP.md

<!-- Generated by claude_md/scripts/bootstrap.sh. This directory is not a git repo, so this
     file is not version-controlled; re-run bootstrap to recreate it. -->
STUB_EOF
  if [ "$DRY" -eq 1 ]; then
    echo "· would write workspace stub $STUB ($siblings sibling repos detected)"
  else
    printf '%s\n' "$STUB_BODY" > "$STUB"
    echo "✓ workspace stub written to $STUB"
  fi
fi

echo
if [ "$DRY" -eq 1 ]; then
  echo "Dry run. Re-run to apply:  bash scripts/bootstrap.sh --write"
else
  cat <<'DONE'
Done. Next:
  1. Open a Claude Code session in any Medoc repo and run /context — you should see the
     managed CLAUDE.md and that repo's own CLAUDE.md under "Memory files".
  2. For each repo you own, wire the invariant guard into its pre-commit hook:
       bash scripts/install-invariant-hook.sh /path/to/your-repo --write
     Commit that change through a normal PR.
  3. Read WORKSPACE-MAP.md once, end to end. It is the map of which repos are dead.
DONE
fi
